name: gestion_ahimet_v2
description: "Sistema de Gestión de Contratos - AHIMET"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.10.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  
  pdf: ^3.12.0
  printing: ^5.13.2
  path_provider: ^2.1.2

  cupertino_icons: ^1.0.8
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_ahimet1.png"
  adaptive_icon_background: "#0A1931"
  adaptive_icon_foreground: "assets/logo_ahimet1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo_ahimet1.png