// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgZ054dZcEnaBBQfMqtvROeh88SGbALHk',
    appId: '1:277415438277:web:518cc97e60dc4117978dac',
    messagingSenderId: '277415438277',
    projectId: 'gestion-ahimet',
    authDomain: 'gestion-ahimet.firebaseapp.com',
    storageBucket: 'gestion-ahimet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_tGO0n_tUD2hnNtLPh6akYhUe9iqTKo',
    appId: '1:277415438277:android:fd20ca2dcb867eb8978dac',
    messagingSenderId: '277415438277',
    projectId: 'gestion-ahimet',
    storageBucket: 'gestion-ahimet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3t8xYk1cgUEwwc99LInwCdzLkA9uXvHk',
    appId: '1:277415438277:ios:27651065228e16d7978dac',
    messagingSenderId: '277415438277',
    projectId: 'gestion-ahimet',
    storageBucket: 'gestion-ahimet.firebasestorage.app',
    iosBundleId: 'com.example.gestionAhimetV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3t8xYk1cgUEwwc99LInwCdzLkA9uXvHk',
    appId: '1:277415438277:ios:27651065228e16d7978dac',
    messagingSenderId: '277415438277',
    projectId: 'gestion-ahimet',
    storageBucket: 'gestion-ahimet.firebasestorage.app',
    iosBundleId: 'com.example.gestionAhimetV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgZ054dZcEnaBBQfMqtvROeh88SGbALHk',
    appId: '1:277415438277:web:78d9c0e835b1bc45978dac',
    messagingSenderId: '277415438277',
    projectId: 'gestion-ahimet',
    authDomain: 'gestion-ahimet.firebaseapp.com',
    storageBucket: 'gestion-ahimet.firebasestorage.app',
  );

}